### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by orhun** [alemidev/scope-tui#1]
Hey, nice project! I was wondering about the licensing - couldn't find any files / text regarding this.

**Comment by alemidev** [comment]
hi, thanks for your interest!

you're right, I'm sorry for releasing scope-tui unlicensed, I procrastinated too much thinking about it (:

i added the MIT license, both inside Cargo.toml and as a separate file!

i think this properly covers the project from now on, let me know if there are any issues or if it becomes necessary to retroactively license older revisions

**Comment by orhun** [comment]
Sounds great, thank you!
